"""empty message

Revision ID: feb4fd65c036
Revises: 23957529124b
Create Date: 2022-06-17 15:23:03.973664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb4fd65c036'
down_revision = '23957529124b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('_password', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_user', '_password')
    # ### end Alembic commands ###
